Controllers/Api/PremiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using VeinsBuster.Models;
using System.Data.Entity;

namespace VeinsBuster.Controllers.Api
{
    public class PremiosController : ApiController
    {
        private ApplicationDbContext _context;

        public PremiosController()
        {
            _context = new ApplicationDbContext();
        }

        //GET /api/Premios
        public IEnumerable<Premio> GetPremios()
        {
            return _context.Premios.Include(t => t.Tipo).Where(p => p.Estatus == true).ToList();
        }

        //GET /api/Premios?Nombre=Consulta
        public Premio GetPremio(string Nombre)
        {
            return _context.Premios.Include(t => t.Tipo).SingleOrDefault(p => p.Nombre == Nombre && p.Estatus == true);
        }
    }
}

Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VeinsBuster.Models;
using VeinsBuster.ViewModels;
using System.Data.Entity;

namespace VeinsBuster.Controllers
{
    public class UsuariosController : Controller
    {
        private ApplicationDbContext _context;

        public UsuariosController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            base.Dispose(disposing);
        }

        // GET: Usuarios
        public ActionResult Index()
        {
            var users = _context.Usuarios.ToList();
            return View(users);
        }

        // GET: Usuarios/Buscar?nombre=Nestor
        public ActionResult Buscar(string nombre)
        {
            var users = _context.Usuarios.Where(u => u.Nombre.Contains(nombre)).ToList();
            return View("Index", users);
        }

        // GET: Usuarios/Perfil/1
        public ActionResult Perfil(int id)
        {
            var user = _context.Usuarios.SingleOrDefault(p => p.Id == id);
            if (user == null)
                return HttpNotFound();
            var viewModel = new PerfilViewModel
            {
                Usuario = user,
                TrPendientes = _context.Transacciones.Include(p => p.Premio).Where(t => t.UsuarioId == id && t.Estatus == false).ToList(),
                TrUsadas = _context.Transacciones.Include(p => p.Premio).Where(t => t.UsuarioId == id && t.Estatus == true).ToList()
            };
            return View(viewModel);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Smart Beauty | Iniciar Sesión</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link href="~/Content/adminlte/css/AdminLTE.min.css" rel="stylesheet" />
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/plugins/iCheck/square/blue.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition login-page">
    @RenderBody()
    <!-- jQuery 2.2.3 -->
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="~/Content/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutSite.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Smart Beauty | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Content/plugins/datatables/dataTables.bootstrap.css">
    <!-- Theme style -->
    <link href="~/Content/adminlte/css/AdminLTE.min.css" rel="stylesheet" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Content/adminlte/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/plugins/iCheck/flat/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="~/Content/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="~/Content/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/Content/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Content/plugins/daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/Content/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Home")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>S</b>B</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Smart</b>Beauty</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- search form -->
                @*<form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Buscar Usuario...">
                            <span class="input-group-btn">
                                <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>*@
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm"}))
                {
                    @Html.AntiForgeryToken()
                    <ul class="sidebar-menu">
                        <li class="header">Menú Principal</li>
                        <li><a href="@Url.Action("Index", "Usuarios")"><i class="fa fa-user text-aqua"></i> <span>Usuarios</span></a></li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-star text-aqua"></i>
                                <span>Premios</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="@Url.Action("Index", "Premios")"><i class="fa fa-circle-o"></i> Lista</a></li>
                                <li><a href="@Url.Action("Nuevo", "Premios")"><i class="fa fa-circle-o"></i> Nuevo</a></li>
                            </ul>
                        </li>
                        @*<li><a href="#"><i class="fa fa-book text-aqua"></i> <span>Historial</span></a></li>*@
                        <li class="header"></li>
                        <li><a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-sign-out text-red"></i> <span>Cerrar Sesión</span></a></li>
                    </ul>
                }
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 1.0.0
            </div>
            <strong>Develop by <a href="http://www.karaokulta.com/">KaraOkulta</a></strong> - 2017
        </footer>
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 2.2.3 -->
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.6 -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- DataTables -->
    <script src="~/Content/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="~/Content/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Content/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="~/Content/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/Content/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Content/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
    <script src="~/Content/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="~/Content/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/Content/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="~/Content/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/adminlte/js/app.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    @*<script src="~/Content/adminlte/js/pages/dashboard.js"></script>*@
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/adminlte/js/demo.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>